# Number of cores allowed on the system
cores: 2

# SnakeMake Conda settings
use-conda: True

# Settings to continue running and keep incomplete
keep-going: True
keep-incomplete: True

# Default rule settings
default-resources:
    cpus_per_task: 6
