# Number of cores allowed on the system
cores: 1

# SnakeMake Conda settings
use-conda: True
conda-frontend: mamba

# Settings to continue running and keep incomplete
keep-going: True
keep-incomplete: True

# Default rule settings
rule *:
    threads: 1