# MPCDF Raven configuration file
local-cores: 1

# SnakeMake Conda settings
use-conda: True
conda-frontend: mamba

# Settings to continue running and keep incomplete
keep-going: True
keep-incomplete: True

# Max number of jobs
jobs: 15

# Queue system
executor: slurm
use-envmodules: True

# Default job requests
default-resources:
    runtime: 1440
    mem_mb_per_cpu: 1666