# Import packages
from os.path import join
from astropy.io import fits

# Names of fields
fields = fits.open('FIELDS/fields.fits')

# List of RATE files
rate = {
    f.name.lower(): [
        join('FIELDS', f.name.lower(), 'RATE', row['filename'].replace('uncal', 'rate'))
        for row in f.data
    ]
    for f in fields[1:]
}

# Final Rule
logs = ['trace']
rule all:
    input:
        expand('FIELDS/{field}/logs/{log}.log',field=rate.keys(),log=logs)

# Sync relevant CRDS cache
onstart:
    shell(r"pixi run --frozen --environment jwst ./workflow/scripts/fetchCRDS.py")

# Download Rule
rule download:
    output:
        ensure('FIELDS/{field}/UNCAL/{file}_uncal.fits', non_empty=True)
    retries: 3
    log:
        'FIELDS/{field}/logs/files/{file}_download.log'
    group:
        'download'
    shell:
        """
        ./workflow/scripts/download.py {output} > {log} 2>&1
        """

# Stage1 Rule
res = workflow.resource_settings.overwrite_resources
stage1_mem_mb = res['stage1']['mem_mb'].value if 'stage1' in res else 0
rule stage1:
    input:
        'FIELDS/{field}/UNCAL/{file}_uncal.fits'
    output:
        'FIELDS/{field}/RATE/{file}_rate.fits'
    log:
        'FIELDS/{field}/logs/files/{file}_stage1.log'
    group:
        'stage1'
    resources:
        mem_mb = lambda _, input: max(20 * input.size_mb, stage1_mem_mb)
    shell:
        """
        pixi run --frozen --environment jwst ./workflow/scripts/stage1.py --scratch {input} {output} >> {log} 2>&1
        """

# Preprocess Rule
rule preprocess:
    input:
        lookup(dpath='{field}', within=rate)
    output:
        'FIELDS/{field}/logs/proc.log'
    log:
        'FIELDS/{field}/logs/proc.log'
    group:
        'imaging'
    shell:
        """
        pixi run --frozen --environment grizli ./workflow/scripts/preprocess.py {wildcards.field} --ncpu {resources.cpus_per_task} > {log} 2>&1
        """

# Mosaic Rule
rule mosaic:
    input:
        'FIELDS/{field}/logs/proc.log'
    output:
        'FIELDS/{field}/logs/mos.log'
    log:
        'FIELDS/{field}/logs/mos.log'
    group:
        'imaging'
    shell:
        """
        pixi run --frozen --environment grizli ./workflow/scripts/mosaic.py {wildcards.field} > {log} 2>&1
        """

# Trace Measurement Rule
rule trace:
    input:
        'FIELDS/{field}/logs/mos.log'
    output:
        'FIELDS/{field}/logs/trace.log'
    log:
        'FIELDS/{field}/logs/trace.log'
    shell:
        """
        pixi run --frozen --environment jwst ./workflow/scripts/trace.py {wildcards.field} > {log} 2>&1
        """

# Contamination Rule
rule contam:
    input:
        'FIELDS/{field}/logs/mos.log'
    output:
        'FIELDS/{field}/logs/contam.log'
    log:
        'FIELDS/{field}/logs/contam.log'
    shell:
        """
        pixi run --frozen --environment grizli ./workflow/scripts/contamination.py {wildcards.field} --ncpu {resources.cpus_per_task} > {log} 2>&1
        """

# Extraction Rule
cpus_per_task = workflow.resource_settings.default_resources.get('cpus_per_task').value
rule extract:
    input:
        'FIELDS/{field}/logs/contam.log'
    output:
        'FIELDS/{field}/logs/extr.log'
    log:
        'FIELDS/{field}/logs/extr.log'
    resources:
        cpus_per_task = lambda wc: cpus_per_task // 2 if wc.field in ['gru-00'] else cpus_per_task
    shell:
        """
        pixi run --frozen --environment grizli ./workflow/scripts/extract.py {wildcards.field} --ncpu {resources.cpus_per_task} > {log} 2>&1
        """

# Redshift Fitting Rule
rule zfit:
    input:
        'FIELDS/{field}/logs/extr.log'
    output:
        'FIELDS/{field}/logs/zfit.log'
    log:
        'FIELDS/{field}/logs/zfit.log'
    shell:
        """
        pixi run --frozen --environment grizli ./workflow/scripts/redshiftFit.py {wildcards.field} --ncpu {resources.cpus_per_task} > {log} 2>&1
        """

# Fitsmap Creation Rule
rule fmap:
    input:
        'FIELDS/{field}/logs/zfit.log'
    output:
        'FIELDS/{field}/logs/fmap.log'
    log:
        'FIELDS/{field}/logs/fmap.log'
    priority:
        lambda wc: len(rate[wc.field])
    shell:
        """
        pixi run --frozen --environment fitsmap ./workflow/scripts/makeFitsmap.py {wildcards.field} --ncpu {resources.cpus_per_task} > {log} 2>&1
        """
