# Run getCluster on startup
#import os
#os.system(f'workflow/scripts/getClusters.py')
with open('CLUSTERS/clusters.txt') as f: clusters = f.read().splitlines()

rule all:
    input:
        directory('RATE')

rule runStage1:
    input:
        directory('UNCAL')
    output:
        directory('RATE')
    conda:'envs/jwst.yaml'  
    resources:
        nodes=1,
        tasks=1,
        cpus_per_task=36,
        mem_mb=2048000,
        slurm_partition='p.huge',
        runtime=1440,
        slurm_extra='--mail-type=ALL --mail-user=hviding@mpia.de -o logs/Stage1.out'
    shell:'./workflow/scripts/runStage1.py --scratch --cpu 36'
