[project]
authors = ['TheSkyentist <raphael.hviding@gmail.com>']
channels = ['conda-forge', 'bioconda']
description = 'NIRISS Pure Paralle Reduction Pipeline'
name = 'NISPureParallel'
platforms = ['osx-arm64', 'linux-64']
version = '1.1.0'

[activation.env]
GRIZLI = '$(pwd)/GRIZLI'
CRDS_PATH = '$(pwd)/CRDS_CACHE'
iref = '$GRIZLI/iref'
jref = '$GRIZLI/jref'
CRDS_CONTEXT = 'jwst_1314.pmap'
CRDS_SERVER_URL = 'https://jwst-crds.stsci.edu'

[feature.grizli.activation.env]
CRDS_READONLY_CACHE = '1'

[tasks]
compute-fields = './resources/scripts/computeFields.py'
make-html = './resources/scripts/makeHTML.py'
sync-html = { cmd = 'scp resources/html5up-phantom/* outthere:html', depends-on = ['make-html'] }
s3-sync = './resources/scripts/clonetoAWS.py'

[feature.grizli.tasks]
grizli-setup = './resources/scripts/setupGrizli.py'

[dependencies]
python = '>=3.11,<3.14'
libarchive = '>=3.7.7,<4'
tqdm = '>=4.67.1,<5'
astropy = '>=7.0.0,<8'
# astroquery = '>=0.4.9,<0.5'

[pypi-dependencies]
sregion = '>=1.4, <2'
spherical-geometry = '>=1.3.2, <2'
astroquery = ">=0.4.9.post1, <0.5"

[environments]
snakemake = { features = ['snakemake'] }
jwst = { features = ['jwst'] }
grizli = { features = ['grizli','jwst'] }
fitsmap = { features = ['fitsmap'] }

[feature.snakemake.dependencies]
scikit-learn = '>=1.6.1,<2'
snakemake = { version = '>=8.27.1,<9', channel = 'bioconda' }
snakemake-executor-plugin-slurm = '>=0.12.0,<0.13'

[feature.jwst.dependencies]
parallel = '>=20241222,<20241223'
threadpoolctl = '>=3.5.0,<4'
numpy = '<2'

[feature.jwst.pypi-dependencies]
columnjump = '>=1.1.0, <2'
jwst = { git = 'https://github.com/spacetelescope/jwst.git' }

[feature.grizli.dependencies]
numba = '>=0.60.0,<0.61'

[feature.grizli.pypi-dependencies]
dust_attenuation = { git = 'https://github.com/karllark/dust_attenuation.git' }
eazy = { git = 'https://github.com/gbrammer/eazy-py.git' }
drizzlepac = '<3.7.1'
reproject = '>=0.14.1, <0.15'
grizli = { git = 'https://github.com/TheSkyentist/grizli.git', branch='dev', extras=['jwst']}

[feature.fitsmap.dependencies]
numpy = "<2"

[feature.fitsmap.pypi-dependencies]
fitsmap = ">=0.11.1, <0.12"
