[project]
authors = ['TheSkyentist <raphael.hviding@gmail.com>']
channels = ['conda-forge', 'bioconda']
description = 'NIRISS Pure Parallel Reduction Pipeline'
name = 'NISPureParallel'
platforms = ['osx-arm64', 'linux-64']
version = '2.1.0'

[activation.env]
GRIZLI = '$(pwd)/GRIZLI'
CRDS_PATH = '$(pwd)/CRDS_CACHE'
iref = '$GRIZLI/iref'
jref = '$GRIZLI/jref'
CRDS_CONTEXT = 'jwst_1413.pmap'
CRDS_SERVER_URL = 'https://jwst-crds.stsci.edu'

[feature.grizli.activation.env]
CRDS_READONLY_CACHE = '1'

[tasks]
compute-fields = './resources/scripts/computeFields.py'
make-html = './resources/scripts/makeHTML.py'
sync-html = { cmd = 'scp resources/html5up-phantom/* outthere:html', depends-on = ['make-html'] }
s3-sync = './resources/scripts/clonetoAWS.py'

[feature.grizli.tasks]
grizli-setup = './resources/scripts/setupGrizli.py'

[feature.jwst.tasks]
crds-sync = 'crds sync --contexts $CRDS_CONTEXT --fetch-references'

[dependencies]
python = ">=3.12.9,<3.14"
libarchive = ">=3.7.7,<4"
tqdm = ">=4.67.1,<5"
astropy = ">=7.0.1,<8"
graphviz = ">=12.2.1,<13"
spherely = ">=0.1.0,<0.2"
shapely = ">=2.1.1,<3"

[pypi-dependencies]
astroquery = ">=0.4.10, <0.5"

[environments]
snakemake = { features = ['snakemake'] }
jwst = { features = ['jwst'] }
grizli = { features = ['grizli'] }
fitsmap = { features = ['fitsmap'] }

[feature.snakemake.dependencies]
scikit-learn = ">=1.6.1,<2"
snakemake = { version = ">=9.1.1,<10", channel = "bioconda" }
snakemake-executor-plugin-slurm = ">=1.1.0,<2"

[feature.jwst.dependencies]
parallel = '>=20241222,<20241223'
threadpoolctl = '>=3.5.0,<4'
numpy = '<2'

[feature.jwst.pypi-dependencies]
columnjump = { git = 'https://github.com/TheSkyentist/jwst-tools.git', subdirectory = 'columnjump' , rev = 'cdc163b' }
jwst = ">=1.19.1, <2"

[feature.grizli.dependencies]
numba = '>=0.60.0,<0.61'

[feature.grizli.pypi-dependencies]
dust_attenuation = { git = 'https://github.com/karllark/dust_attenuation.git' , rev ='02a1067'}
eazy = { git = 'https://github.com/gbrammer/eazy-py.git' , rev = '292172c' }
drizzlepac = '<3.7.1'
reproject = '>=0.14.1, <0.15'
grizli = { git = 'https://github.com/TheSkyentist/grizli.git', extras = ['jwst'], rev = '8e0ae2f'}

[feature.fitsmap.dependencies]
numpy = "<2"

[feature.fitsmap.pypi-dependencies]
fitsmap = ">=0.11.1, <0.12"
