[project]
authors = ["TheSkyentist <raphael.hviding@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "NIRISS Pure Paralle Reduction Pipeline"
name = "NISPureParallel"
platforms = ["osx-arm64"]
version = "1.0.0"

[activation]
scripts = ["resources/setupShell.sh"]

[tasks]
computeFields = "./resources/scripts/computeFields.py"
clean = "rm -r .snakemake/conda"

[dependencies]
python = ">=3.12.8,<3.13"
pip = ">=24.3.1,<25"
tqdm = ">=4.67.1,<5"
conda = ">=24.11.2,<25"
scipy = ">=1.15.0,<2"
astropy = ">=7.0.0,<8"
astroquery = ">=0.4.7,<0.5"
libarchive = ">=3.7.7,<4"
scikit-learn = ">=1.6.0,<2"
snakemake = { version = ">=8.26.0,<9", channel = "bioconda" }
snakemake-executor-plugin-slurm = ">=0.11.2,<0.12"

[pypi-dependencies]
sregion = ">=1.4, <2"
spherical-geometry = ">=1.3.2, <2"

[feature.grizli.activation]
scripts = ["resources/setupShell.sh"]

[feature.grizli.tasks]
setup = "./resources/scripts/setupGrizli.py"

[feature.grizli.pypi-dependencies]
grizli = { git = "https://github.com/TheSkyentist/grizli.git", rev="dev", extras=["jwst"]}

[environments]
grizli = {features = ["grizli"]}
